sudo: required

services:
  - docker

language: go

go:
  - 1.5

before_install:
 - go get github.com/constabulary/gb/...
 - docker build -t gobwas/outyet .
 - docker run -d --publish 127.0.0.1:80:8080
 - docker ps -a
 - docker stop gobwas/outyet

install: gb vendor update --all

script: go test -v ./src/*