sudo: required

services:
  - docker

language: go

go:
  - 1.5

before_install:
 - go get github.com/constabulary/gb/...

install: gb vendor update --all

script: go test -v ./src/*

after_success:
 - docker build -t gobwas/outyet .
 - docker run -d -p 127.0.0.1:80:8080 gobwas/outyet
 #- docker run -d -p 127.0.0.1:8080:8080 gobwas/outyet /bin/sh -c "cd /root/outyet; go test -v ./src/*"
 - docker ps -a
 #- docker run gobwas/outyet /bin/sh -c "cd /root/outyet; go test -v ./src/*"
 - curl --retry 5 --retry-delay 5 -v http://127.0.0.1:80
 - docker stop gobwas/outyet
 - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - docker push gobwas/outyet
